### ISSUE TITLE
Ensure Bootstrap Server and Landing Zone can be deployed on Organization node

### ISSUE THREAD

**Issue by sunderhill-gft** [tranquilitybase-io/tb-gcp#181]
Ensure Bootstrap Server and Landing Zone can be deployed on Organization node

**Comment by oscarmon7** [comment]
In order to allow the deployment of TB under the Org level the following changes will be done.

In config creator:
1. create TB folder
2. create the bootstrap project in the TB folder

In TF:
1. Remove the creation of the TB folder
2. Pass the TB folder ID as parameter rather than the Parent Folder Id

**Comment by connor-mcshane** [comment]
Still working on this, need to test.

**Comment by connor-mcshane** [comment]
Closed as split into #220 and #221
