### ISSUE TITLE
[Issue] Eagle Console must be contactable via a private internal IP address

### ISSUE THREAD

**Issue by scottholmangft** [tranquilitybase-io/tb-gcp#256]
SH to update

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by andy12838729** [comment]
I think this could be improved by making the default as private, but with an option from the Eagle console to be public (https)

**Comment by alexdgft** [comment]
Some questions around this:
1. If the plan for this is to use an internal IP then the Istio installation will have to be pulled out into a separate script as the GKE attached version doesn't give you a way to use an internal IP.
2. Is the plan for Istio to do SSL termination or SSL passthrough? Both methods are available in Istio and you can then either present the certificate to Istio or to the EC containers. Is there a preference?

**Comment by connor-mcshane** [comment]
@scottholmangft  to add to Alex's [1] point. Narish advised for us to split up the terraform state anwyways (like what I was alluding to earlier). So would definitely agree with Alex here.

**Comment by alexdgft** [comment]
Moving the Istio install out of the GKE bit might make migration between cloud providers easier as well? Not sure if that's something worth considering.

In terms of being able to pull Istio out into a separate file, the method of choice has changed with Istio 1.4 and onwards to using istioctl instead of helm charts for installation. The helm charts are still supported for backwards compatibility but will be deprecated 'in the future'. For this reason I think we should all agree on using istioctl. The only update I've seen on GCP docs about using istioctl is from their Anthos documentation but it at least shows the basic idea: https://cloud.google.com/anthos/gke/docs/aws/how-to/ingress#private_1 

Depending on the final decision to always use a base version of Istio or not, we would also need to pull any Istio related config out of the eagle-console.yaml file such as destination rules and virtual services to allow it to work with plain Kubernetes. There is currently a virtual service that routes traffic to the /api endpoint to Houston which would need to be changed as Kubernetes doesn't have support for uri based routing.

For the TLS question, do people build the eagle console image themselves or do we push it to a public image repo? If the later it would probably be easier to do TLS termination as then the cert that is exposed to the end user will be easier to control for the eagle console admin. Whether to use SSL on the backend is a different discussion, I would normally say yes but it might be more hassle than its worth in this case.

**Comment by Salles-FA** [comment]
Hi @alexdgft,

> For the TLS question, do people build the eagle console image themselves or do we push it to a public image repo? If the later it would probably be easier to do TLS termination as then the cert that is exposed to the end user will be easier to control for the eagle console admin. Whether to use SSL on the backend is a different discussion, I would normally say yes but it might be more hassle than its worth in this case.

The image can be built in a CI process using this [Dockerfile](https://github.com/tranquilitybase-io/tb-eagle-console/blob/master/Dockerfile) using the sequence of commands described [here](https://github.com/tranquilitybase-io/tb-eagle-console#gcp-build-commands). Currently I'm manually building this [Dockerfile.dev](https://github.com/tranquilitybase-io/tb-eagle-console/blob/master/Dockerfile.dev) at regular basis after all manual tests passing. 

If you are about to make this CI build, I strongly recommend you to do it after we have this [BugFix issue](https://github.com/tranquilitybase-io/tb-eagle-console/issues/115) closed.

> Depending on the final decision to always use a base version of Istio or not, we would also need to pull any Istio related config out of the eagle-console.yaml file such as destination rules and virtual services to allow it to work with plain Kubernetes. There is currently a virtual service that routes traffic to the /api endpoint to Houston which would need to be changed as Kubernetes doesn't have support for uri based routing.

I'm not sure... I'm wondering if it's possible to configure the Kubernetes Load Balancer to "Reverse Proxy" this '/api' traffic to the correct API pod, and '*' to the UI. Also the TLS could be configured in K8s Load Balancer.

**Comment by alexdgft** [comment]
> I'm not sure... I'm wondering if it's possible to configure the Kubernetes Load Balancer to "Reverse Proxy" this '/api' traffic to the correct API pod, and '*' to the UI. Also the TLS could be configured in K8s Load Balancer.

Sorry, I should clarify. A Kubernetes service (as far as I know) doesn't have support for URI routing. Could always use a different ingress controller such as haproxy or nginx to do the routing instead of Istio.

Thinking about the cert more, it would make more sense to offload the SSL to the ingress. There you can then either use a file mount or a secret inside the cluster to store the cert.

**Comment by Salles-FA** [comment]
> Could always use a different ingress controller such as haproxy or nginx to do the routing instead of Istio.

@alexdgft Please confirm if this is the best choice and we can open a new issue on [tb-eagle-console](https://github.com/tranquilitybase-io/tb-eagle-console) repo to make this change. We can add a new folder (e.g. "build/ingressGateway/") to these Dockerfile and "nginx.conf".

**Comment by alexdgft** [comment]
Step 1) Decide on using Istio or not. Scott wants to use it to demonstrate knowledge, if not using it however choose an appropriate replacement for the ingress controller such as nginx: https://www.nginx.com/products/nginx/kubernetes-ingress-controller
2) Move the installation of Istio outside of GKE specific config. Disable the istio_enabled flag in the GKE module and instead run istioctl to install Istio.
All configuration will need to be inside a yaml file that gets passed to istioctl. This only needs to specify changes from the default.
For example the below will set up an internal load balancer.
```yams
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          serviceAnnotations:
            cloud.google.com/load-balancer-type: "internal"
        ## ILB on GCP has a maxiumum of 5 ports unless you allow all ports. GKE however doesn't support creating a LB that allows all ports unless created manually: https://cloud.google.com/load-balancing/docs/internal.
        ## This is a cut down list of ports used by Istio, others may be required.
        service:
          ports:
          - name: status-port
            port: 15020
            targetPort: 15020
          - name: http2
            port: 80
            targetPort: 80
          - name: https
            port: 443
```
istioctl manifest generate -f <above_yaml_filename>> istioinstall.yaml
istioctl manifest apply -f istioinstall.yaml

NB The above is untested due to time constraints.

You will also need to turn on automatic sidecar injection otherwise there will be no way for Istio to route traffic to the pods. This can be done either by labelling the namespace once Istio is installed with istio-injection=enabled or by enabling the sidecar injector in the istioctl manifest.

**Comment by RDHA-GFT** [comment]
Split option to make publicly accessibly into separate issue #311

**Comment by stuartrl07** [comment]
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          serviceAnnotations:
            cloud.google.com/load-balancer-type: "internal"
        ## ILB on GCP has a maxiumum of 5 ports unless you allow all ports. GKE however doesn't support creating a LB that allows all ports unless created manually: https://cloud.google.com/load-balancing/docs/internal.
        ## This is a cut down list of ports used by Istio, others may be required.
          service:
            ports:
            - name: status-port
              port: 15020
              targetPort: 15020
            - name: http2
              port: 80
              targetPort: 80
            - name: https
              port: 443
