### ISSUE TITLE
Packer image built from a branch gives terraform init error

### ISSUE THREAD

**Issue by arvindclement** [tranquilitybase-io/tb-gcp#333]
**Describe the bug**
While using branch image to deploy the landing zone you get the following error when you run the tb-welcome script 

Time start: 2020-06-02 23:37:43
Creating gs://tf-export-3745c3a7/...
Folder is 758737119140
Billing Id is 01A2F5-73127B-50AE5B
Setting [bootstrap-sa@bootstrap-3745c3a7.iam.gserviceaccount.com] as active account
Updated property [core/account].
Terraform init
Initializing modules...

Initializing the backend...
Backend configuration changed!

Terraform has detected that the configuration specified for the backend
has changed. Terraform will now check for existing state in the backends.

Error: Error inspecting states in the "gcs" backend:
    querying Cloud Storage failed: storage: bucket doesn't exist

Prior to changing backends, Terraform inspects the source and destination
states to determine what kind of migration steps need to be taken, if any.
Terraform failed to load the states. The data in both the source and the
destination remain unmodified. Please resolve the above error and try again.

Terraform init failed.

**To Reproduce**
1. Create a branch 
2. Do a deploy
3. While deploying the boostrap project choose the image referring to your branch in tb-marketplace-dev for e.g https://www.googleapis.com/compute/v1/projects/tb-marketplace-dev/global/images/tranquility-base-bootstrap-issue-329 and change the source image in tranquility-base.jinja
3. Run the gcloud deployment 
4. Log on to the terraform server and go to /opt/tb/repo/tb-gcp-tr/landingZone/
5. run ./tb-welcome you will see this error

**Expected behavior**
The tb-welcome should run and deploy the landing zone with the changes you have made in your branch

Additional context
Suspect it is got to do with IAM issues to the projects in the packer image.

**Comment by zi01** [comment]
Followed the steps to reproduce the error and got the expected behaviour - Terraform init passed. 

Initializing the backend might potential fail if deploying into existing project so can't create the bucket as not unique, have state file in the image or account did not have enough iam perms to create the bucket.

**Comment by zi01** [comment]
Followed the steps to reproduce the error and got the expected behaviour - Terraform init passed from a packer image built from a branch.

Initializing the backend might potentially fail if deploying into existing project so can't create the bucket as not unique, have state file in the image or account did not have enough iam perms to create the bucket.
