### ISSUE TITLE
[Feature] Configure Eagle Console to use HTTPS

### ISSUE THREAD

**Issue by scottholmangft** [tranquilitybase-io/tb-gcp#334]
**Is your feature request related to a problem? Please describe.**
Eagle Console is currently accessible via insecure HTTP. HTTPS needs to be implemented to encrypt traffic between client browser, and Eagle Console

**Describe the solution you'd like**
Configure Eagle Console to enforce use of HTTPS

**Describe alternatives you've considered**
none

**Additional context**
Other issues have similar features requests. This issue has been given its own issue to enable focussed development for faster resolution.

**Comment by scottholmangft** [comment]
#311 includes investigating into enabling HTTPS.

**Comment by stuartrl07** [comment]
Have started looking at this but need to hand over.

First step is to make the traffic go via HTTPS, to do this need to change the eagle_console.yaml file in the following places:
eagle console deployment to container port 443 instead of 80

the gateway to this:
`---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mygateway
spec:
  selector:
    istio: private-ingressgateway # use istio default controller
  servers:
    - port:
        number: 443
        name: http
        protocol: HTTPS
      hosts:
        - "*"`

The eagle console virtual service to:
`---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: eagleconsole
spec:
  hosts:
    - "*"
  gateways:
    - mygateway
  http:
    - route:
        - destination:
            host: eagleconsole
            port:
              number: 443`

**Comment by stuartrl07** [comment]
To enable SSL offloading you need to follow instructions here:
https://istio.io/docs/tasks/traffic-management/ingress/secure-ingress/

Change the gateway in eagle_console.yaml to have:
`tls:
      mode: SIMPLE
      credentialName: ec-tls-credential`

Where you have created certificate and keys for ssl and stored them in a secret on the ec cluster using:
 kubectl create -n istio-system secret tls ec-tls-credential --key=example.com.key --cert=example.com.crt

This will use SSL offloading with these credentials, but they may be needed to be added to the bastion vm credentials to be trusted, need to investigate that part still

**Comment by stuartrl07** [comment]
@RDHA-GFT Have assigned to you so you can find someone else to pick it up. Thanks

**Comment by afamgft** [comment]
The required changes have been made to allow traffic go via HTTPS and to enable SSL offloading.  (issue-334). This needs to be tested before merging to master. Need assistance on how to deploy TB from git branch other than master

**Comment by afamgft** [comment]
Changes have been tested and it works fine
